link_ClickOnPackage="xpath://span[text()='Package']"
link_ClickOnCreatePackage="xpath://a[contains(text(),'Create')]"
btn_Prepaid="id:prepaid"
btn_Postpaid="id:postpaid"
txt_PerActiveStudentCharges="name:student_charge"
txt_PerActiveStaffCharges="name:staff_charge"
txt_PackageName="xpath://input[@placeholder='Package Name']"
txt_Description="xpath://textarea[@placeholder='Description']"
txt_Tagline="name:tagline"
txt_Days="name:days"
txt_NoOfStudents="name:no_of_students"
txt_NoOfStaff="name:no_of_staffs"
txt_Charges="name:charges"
checkbox_HighlightPackage="name:highlight"

# Features
label_AnnouncementManagement="xpath://label[text()='Announcement Management']"
label_AssignmentManagement="xpath://label[normalize-space()='Assignment Management']"
label_AttendanceManagement="xpath://label[normalize-space()='Attendance Management']"
label_ChatModule="xpath://label[normalize-space()='Chat Module']"
label_ExamManagement="xpath://label[normalize-space()='Exam Management']"
label_ExpenseManagement="xpath://label[normalize-space()='Expense Management']"
label_FeesManagement="xpath://label[normalize-space()='Fees Management']"
label_HolidayManagement="xpath://label[normalize-space()='Holiday Management']"
label_IDCardCertificateGeneration="xpath://label[normalize-space()='ID Card - Certificate Generation']"
label_LessonManagement="xpath://label[normalize-space()='Lesson Management']"
label_SchoolGalleryManagement="xpath://label[normalize-space()='School Gallery Management']"
label_SliderManagement="xpath://label[normalize-space()='Slider Management']"
label_StaffLeaveManagement="xpath://label[normalize-space()='Staff Leave Management']"
label_StaffManagement="xpath://label[normalize-space()='Staff Management']"
label_TimetableManagement="xpath://label[normalize-space()='Timetable Management']"
label_WebsiteManagement="xpath://label[normalize-space()='Website Management']"
btn_Submit="id:create-btn"

#   List Package
btn_UpdateRank="id:reorder"

